# Generated by Django 5.2.16 on 2026-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostories', '0009_geostorylayer_style_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='geostory',
            name='about_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Here you can provide information about yourself and your perspective (e.g. your occupation, where you live, and the narrative background or paradigm of your Geostory).',
                verbose_name='About the Author/Transparency (Public)',
            ),
        ),
    ]
